[package]
name = "tutorial"
version = "0.1.0"
authors = ["Huon Wilson <Huon.Wilson@data61.csiro.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
